"""add normalized question hash

Revision ID: 48674f6b294e
Revises: b3c0f00100d5
Create Date: 2026-09-22 04:28:46.196999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48674f6b294e'
down_revision: Union[str, Sequence[str], None] = 'b3c0f00100d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('normalized_text_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_questions_normalized_text_hash'), 'questions', ['normalized_text_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_normalized_text_hash'), table_name='questions')
    op.drop_column('questions', 'normalized_text_hash')
    # ### end Alembic commands ###
