"""enforce question hash uniqueness

Revision ID: afde914a3f7b
Revises: 48674f6b294e
Create Date: 2026-09-22 04:48:53.706765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afde914a3f7b'
down_revision: Union[str, Sequence[str], None] = '48674f6b294e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_normalized_text_hash'), table_name='questions')
    op.create_index(op.f('ix_questions_normalized_text_hash'), 'questions', ['normalized_text_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_normalized_text_hash'), table_name='questions')
    op.create_index(op.f('ix_questions_normalized_text_hash'), 'questions', ['normalized_text_hash'], unique=False)
    # ### end Alembic commands ###
